[package]
name = "syslog"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.2"
serde_json = "1.0.59"
sysinfo = "0.19.2"
